### ISSUE TITLE
[Feature] [WPF] Add DataMatrix and Code128 WPF Control

### ISSUE THREAD

**Issue by Int32Overflow** [huysentruitw/barcoder#13]
Add DataMatrix and Code128 WPF Control

**Comment by huysentruitw** [comment]
As mentioned on the PR, WPF is not something I want to support in this library.

**Comment by Int32Overflow** [comment]
Ok no problem. I added a new repository [Barcoder.WPF](https://github.com/Int32Overflow/Barcoder.WPF)
