### ISSUE TITLE
Unicode in QR

### ISSUE THREAD

**Issue by gmjn** [huysentruitw/barcoder#16]
In QR code, my Norwegian characters are wrong (æøåÆØÅ). I checked the code in the barcoder/src/Barcoder/Qr/InternalEncoders/UnicodeEncoder.cs file and found the following error.
1. Byte order mark is missing.
2. When data length is set, content length is used and not data length.

I corrected this in the code and now my Norwegian letters work fine. Here is my code now:

    internal sealed class UnicodeEncoder : InternalEncoderBase
    {
        public override (BitList, VersionInfo) Encode(string content, ErrorCorrectionLevel errorCorrectionLevel)
        {
            bool insertBom = false; // Insert Byte order mark (BOM) for UTF-8

            if (content == null) throw new ArgumentNullException(nameof(content));

            foreach (char item in content)
            {
                if (item > 127) // Check if BOM is needed
                {
                    insertBom = true;
                    break;
                }
            }
            
            byte[] data = System.Text.Encoding.UTF8.GetBytes(content);
            int dataLength = insertBom ? data.Length + 3 : data.Length;

            EncodingMode encodingMode = EncodingMode.Byte;
            var versionInfo = VersionInfo.FindSmallestVersionInfo(errorCorrectionLevel, encodingMode, dataLength * 8);
            if (versionInfo == null)
                throw new InvalidOperationException("Too much data to encode");

            var bits = new BitList();
            bits.AddBits((uint)encodingMode, 4);
            bits.AddBits((uint)dataLength, versionInfo.CharCountBits(encodingMode));

            if (insertBom) // Insert BOM
            {
                bits.AddByte(239);
                bits.AddByte(187);
                bits.AddByte(191);
            }

            foreach (var b in data)
                bits.AddByte(b);
            AddPaddingAndTerminator(ref bits, versionInfo);
            return (bits, versionInfo);
        }
    }

**Comment by huysentruitw** [comment]
Thanks for raising this issue. Are you willing to create a unit-test with fix as a pull-request or do you want me to take care of it?

**Comment by jbartlau** [comment]
@huysentruitw This fix causes an issue when using the QrEncoder to encode EPC barcodes. They don't expect the byte order mark to be present and fail validation. The behavior should be configurable.

**Comment by huysentruitw** [comment]
@jbartlau please elaborate more. Can you given an example or write a failing test?

**Comment by jbartlau** [comment]
@huysentruitw I cannot provide a failing test. However, the EPC standard demands an UTF-8 encoding if e. g. Umlauts are used in the QR code content. But most banking apps fail to parse the EPC if the UTF-8 BOM is present. See [here](https://www.europeanpaymentscouncil.eu/sites/default/files/kb/file/2024-03/EPC069-12%20v3.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20an%20SCT.pdf) for the specs. The character set used is part of the barcode's payload.

I was unable to find a definitve answer on "may the content contain a BOM or not", however out of 10 banking apps I tested, 10 refused to accept the code with a BOM.

I cannot provide a failing test as the QR itself is just fine - just the banking apps do not accept it. This is why I think it should be parametrizable.
