### ISSUE TITLE
Set width and height of barcode

### ISSUE THREAD

**Issue by Mt-Perazim** [huysentruitw/barcoder#18]
I'm using your barcode generator and I want to thank you for sharing it with us! Right now I'm struggling with one thing. Is it done on purpose so that the width and height cannot be set? I wanted to set the width of the generated bar code and tried that by accessing Bounds, which is a struct...so its meant to be only readable.
**Is there a way to set the width and heigt of the barcode before generating it?**

**Comment by huysentruitw** [comment]
To be honest, I didn't think about that as I originally only had a SVG generator where width and height of the output doesn't matter as it is scalable in your application. Am I right you're using the PNG renderer?

**Comment by Mt-Perazim** [comment]
No I'm using the SvgRenderer. I guess I'm gonna go a different way. Depending on what you do with the svg, width and hight might not matter, like you said. But for my case, where I have to give the data to a laser I need to have coordinates.
Thanks for responding so quickly!

**Comment by huysentruitw** [comment]
@arsi0001 were you able to solve it a different way or is their still any help needed from my side?

**Comment by Mt-Perazim** [comment]
Hey, I changed my mind and decided to take the bitarray from the generated barcode and creating rectangles, which I fill then with lines. This way I can also set the widht and height by my self.

**Comment by huysentruitw** [comment]
Ok. Closing this issue for now. If anything else, feel free to reopen or create a new issue.
