### ISSUE TITLE
[Feature] [DataMatrix] Support for rectangular DataMatrix

### ISSUE THREAD

**Issue by Int32Overflow** [huysentruitw/barcoder#22]
I need the function for rectangular DataMatrix codes as described in ISO/IEC 16022:2006.

![grafik](https://user-images.githubusercontent.com/20139038/97972755-4c40a580-1dc5-11eb-81fd-0e15510d7cd3.png)

**Mapping table for rectangular DataMatrix (page 65):**

![grafik](https://user-images.githubusercontent.com/20139038/97972572-0257bf80-1dc5-11eb-99eb-c73584c3b3be.png)

**Comment by huysentruitw** [comment]
How fast do you need this? Can you submit a PR for it or do you want me to implement it? Is there any budget?

**Comment by Int32Overflow** [comment]
@huysentruitw I will submit a PR the next days :-)

**Comment by huysentruitw** [comment]
Thanks for the addition.
