### ISSUE TITLE
Is it possible to use this in SSRS

### ISSUE THREAD

**Issue by VF-JustinMolnar** [huysentruitw/barcoder#26]
Hi,

We have tested this in a C# app and it worked well. Thank you.

Do you know if it is possible to use this in a SSRS project (Reporting Services)?

Thank you,
Justin

**Comment by huysentruitw** [comment]
I'm late to the party here, but I have no idea how to make this work with SSRS (I don't have any experience). But perhaps you have figured it out yourself by now, so closing this issue. Feel free to reopen if there's anything I could help you with.
