### ISSUE TITLE
Barcode numbers not displayed sometimes

### ISSUE THREAD

**Issue by rashazayed85** [huysentruitw/barcoder#27]
Hi,
Im using barcoder in Xamarin forms, to print out a bar code, working fine on some machines
and on others not... I got the code image without the numbers below as attached
![barcode](https://user-images.githubusercontent.com/83224533/124350687-5c2fb400-dbf6-11eb-8297-b6550e02bff6.JPG)

Any help?

**Comment by huysentruitw** [comment]
Barcoder uses the font-family "arial", perhaps that font is not available on those machines?

**Comment by rashazayed85** [comment]
But the [Arial] font is available in windows already

**Comment by huysentruitw** [comment]
Any update on this? I'm not using Xamarin forms myself, so hard to simulate this. Will close this issue in the meantime as it doesn't occur in other tests. Feel free to send a PR if something needs to be fixed.
