### ISSUE TITLE
Port Data Matrix

### ISSUE THREAD

**Issue by huysentruitw** [huysentruitw/barcoder#3]

**Comment by Int32Overflow** [comment]
Hey,

what's your schedule for DataMatrix support? I would support you...

**Comment by huysentruitw** [comment]
I think I can have datamatrix ported in a week or so. When do you need it?

**Comment by Int32Overflow** [comment]
Yeah, that wouldn't be bad if it's okay for you. I need the DataMatrix code in the next 2 weeks

**Comment by huysentruitw** [comment]
I'll put it on highest priority!

**Comment by Int32Overflow** [comment]
Thank you :blush:

**Comment by huysentruitw** [comment]
@Int32Overflow version 1.0.0.58 contains support for DataMatrix and should be available on NuGet in a couple of minutes. Please give it a shot!

**Comment by Int32Overflow** [comment]
That's great :-) I'll test it out. Do you know which ECC version is used?

**Comment by huysentruitw** [comment]
It's ECC 200, based on Reed-Solomon.

**Comment by Int32Overflow** [comment]
OK :+1:
An other question: Is FNC1 supported?

**Comment by huysentruitw** [comment]
Currently not. But shouldn't be that hard to add.
