### ISSUE TITLE
QR Code render thows an exception

### ISSUE THREAD

**Issue by tinohager** [huysentruitw/barcoder#30]
I installed these two packages as described in the documentation, the error thows in my netcoreapp3.1

- Barcoder
- Barcoder.Renderer.Image

```
var barcode = QrEncoder.Encode(qrcode.Content, Barcoder.Qr.ErrorCorrectionLevel.M, Encoding.Auto);
var renderer = new ImageRenderer(imageFormat: Barcoder.Renderer.Image.ImageFormat.Png);

using (var ms = new MemoryStream())
{
	renderer.Render(barcode, ms);
	var imageData = ms.ToArray();
	this._skCanvas.DrawBitmap(SKBitmap.Decode(imageData), x, y);
}
```

![image](https://user-images.githubusercontent.com/8215186/129492370-622008f8-c3cf-4b3f-b275-5281fcc8ae74.png)

**Comment by huysentruitw** [comment]
This library is still depending on a beta version of the SixLabors.ImageSharp package. I think we should update it to a non-beta release if that's possible before trying anything else.

Apart from that, I think this error can happen when your project also references the same NuGet package, but a different version.

**Comment by tinohager** [comment]
On a clean project it works.

![image](https://user-images.githubusercontent.com/8215186/129621372-3d936aa8-5ee2-41bb-98b7-fe1dfe644f5f.png)
