### ISSUE TITLE
System.ArgumentException: 'Content length should be between 1 and 80 but got 0 (Parameter 'content')'

### ISSUE THREAD

**Issue by AlaaTarekSelim** [huysentruitw/barcoder#31]
when generating code 128 with option gs1 = true it gives this error in 
 Code128Encoder.Encode("122345678901", true, true);

**Comment by jaszczykj** [comment]
same issue

**Comment by jaszczykj** [comment]
> same issue

it's works but you must enter content in format like in the test: "(241)ABC(10)123"

**Comment by huysentruitw** [comment]
Feel free to open a PR in order to fix this. Closing this issue for now.
