### ISSUE TITLE
Rectangular Datamatrix

### ISSUE THREAD

**Issue by morisbozzetto** [huysentruitw/barcoder#35]
Hi,

First of all, amazing work @huysentruitw. 
Is it possible to create rectangular datamatrixes (e.g. 36 columns 12 rows) ?

Thanks

**Comment by huysentruitw** [comment]
That is supported, yes.

The [`Encode`](https://github.com/huysentruitw/barcoder/blob/develop/src/Barcoder/DataMatrix/DataMatrixEncoder.cs#L10) method of the DataMatrixEncoder has optional variables to set either the number of rows or number of columns to a fixed number.
