### ISSUE TITLE
Update to SixLabors.ImageSharp.Drawing 2.1.1

### ISSUE THREAD

**Issue by daze99** [huysentruitw/barcoder#43]
Are there any plans to update SixLabors.ImageSharp.Drawing to version 2.1.1?

Calling ImageRenderer.Render(IBarcode barcode, Stream outputStream) produces the error:
```
System.MissingMethodException: Method not found: 'Void SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder.set_Quality(System.Nullable`1<Int32>)'.
```
And also the author issued a [advisory report](https://github.com/advisories/GHSA-65x7-c272-7g7r) because a vulnerability was found.

**Comment by huysentruitw** [comment]
Version 3.0 has been released that targets ImageSharp 2.1.3.
