### ISSUE TITLE
Code128 cannot read by scanner

### ISSUE THREAD

**Issue by Int32Overflow** [huysentruitw/barcoder#7]
Hey,
the Code128Encoder is not working :-(

```
            var code128 = Code128Encoder.Encode("123", false);
            var renderer = new ImageRenderer();
            using (var stream = new FileStream("output.png", FileMode.Create))
                renderer.Render(code128, stream);
            Process.Start("output.png");
```

I tried to read the code, but this code seems to be not valid!

**Comment by huysentruitw** [comment]
Probably because your reader expects a checksum. Try `Code128Encoder.Encode("123", true)` instead.

**Comment by Int32Overflow** [comment]
Thank you very much for the message. Right, that was the problem. Now the code can be read.

**Comment by huysentruitw** [comment]
Welcome. Don't forget to ⭐️ this project if you like it 😎 Thanks!
