### ISSUE TITLE
[Feature] [DataMatrix] Support GS1

### ISSUE THREAD

**Issue by Int32Overflow** [huysentruitw/barcoder#9]
Support for FNC1

**Comment by Int32Overflow** [comment]
@huysentruitw Do you know how to get GS1 functionality into the DataMatrix?

**Comment by Int32Overflow** [comment]
@huysentruitw Sorry to bother you. When would you have time for the implementation?

**Comment by huysentruitw** [comment]
Hi @Int32Overflow thank you for your patience! I would like to know how you would see the usage? How will we pass the AI's with their data? I was thinking to allow strings like `(01)03453120000011(17)190704` and pass a true to `gs1ModeEnabled` in `public static IBarcode Encode(string content, int? fixedNumberOfRows = null, bool gs1ModeEnabled = false)`. Would that be ok, or do you have something else in mind?

**Comment by Int32Overflow** [comment]
It is sufficient if a certain string sequence is existing in the string for GS1. For example `(01)03453120000011\{FNC1}(17)190704`

**Comment by huysentruitw** [comment]
If I understand correctly, `FNC1` control char is only added to end non-predefined length AI's. My idea would be to do that implicitly, so you don't have to add `FNC1` yourself in the string.

**Comment by Int32Overflow** [comment]
Yes, that's correct. Then you'll have to parse the entire string.

For me the solution with the string "\{FNC1}" would be more useful... Especially because the solution to parsing the string will be a great deal of effort!

**Comment by huysentruitw** [comment]
Just a reminder, I'm not forgetting this, time is just very limited ATM.

**Comment by huysentruitw** [comment]
@Int32Overflow thank you very much for your patience. GS1 support has been added to the DataMatrix encoder.

Usage:

```C#
var dataMatrix = DataMatrixEncoder.Encode("(01) 0 0614141 99999 6 (90) 1234567890", gs1ModeEnabled: true)
```

This will be available as of version 1.0.0.61

Enjoy! :tada:

**Comment by huysentruitw** [comment]
Had to fix a bug, so please test with version 1.0.0.63

**Comment by Int32Overflow** [comment]
@huysentruitw Thank you very much for the implementation. 

But I think I found a bug in the GS1 implementation: Application Identifiers with `variable measure trade item` may not work. For example AI "3100" (https://www.gs1.org/standards/barcodes/application-identifiers/3100?lang=en)

Another question: We could also use this GS1 parser for the Code128, couldn't we?

**Comment by huysentruitw** [comment]
Unknown AI's will be terminated by a FNC1 char, so it probably will work although the FNC1 could have been omitted.

For your Code128 question, I think so yes. I'll look into that.

**Comment by Int32Overflow** [comment]
> 
> 
> Unknown AI's will be terminated by a FNC1 char, so it probably will work although the FNC1 could have been omitted.

But this is not a valid GS1 DataMatrix code. AI 3100 has a fixed size and don't required any FNC1 seperator

**Comment by huysentruitw** [comment]
Indeed, they don't require it, but it is allowed to use the FNC1 separator either way if I'm correct. It's just not that optimal.

**Comment by Int32Overflow** [comment]
> 
> 
> Indeed, they don't require it, but it is allowed to use the FNC1 separator either way if I'm correct. It's just not that optimal.

Should I rewrite the parser to support the GS1 AI 3100? Maybe I have a solution for that.

**Comment by huysentruitw** [comment]
Already fixed in https://github.com/huysentruitw/barcoder/commit/2c943943c953316b43b159545d833fd3ebb98ece
